# Generated by Django 3.0.6 on 2020-06-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0004_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unsent'), (1, 'Sending'), (2, 'Sent'), (3, 'Failed')], default=0),
        ),
    ]
