# Generated by Django 3.2.13 on 2022-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0004_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
