# Generated by Django 3.2.16 on 2022-12-07 15:55

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('birdsong', '0006_auto_20220428_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='The name of the campaign', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='receipts',
            field=models.ManyToManyField(through='birdsong.Receipt', to='birdsong.Contact', verbose_name='receipts'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(0, 'unsent'), (1, 'sending'), (2, 'sent'), (3, 'failed')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.TextField(verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='birdsong.ContactTag', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
