# Generated by Django 3.2.16 on 2023-03-20 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('birdsong', '0008_translation_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='contact',
            name='confirmed_at',
            field=models.DateTimeField(null=True, verbose_name='confirmed at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
        migrations.AddField(
            model_name='contact',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='BirdsongSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('double_opt_in_enabled', models.BooleanField(default=False, help_text='Attention: By enabling this, unconfirmed contacts older than a week get deleted when creating, editing or copying a campaign. Contacts are unconfirmed by default.', verbose_name='Enable double opt-in')),
                ('confirmation_email_subject', models.CharField(default='Confirm newsletter registration', max_length=150, null=True, verbose_name='Subject of confirmation e-mail')),
                ('confirmation_email_body', wagtail.fields.RichTextField(default='Click the following link if you want register for our newsletter. Otherwise no action is neccessary.', help_text='This Text is part of the e-mail that is sent after registration for a campaign', null=True, verbose_name='Content of confirmation e-mail')),
                ('campaign_confirmation_redirect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Redirect page after confirmation of campaign signup')),
                ('campaign_signup_redirect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Redirect page after signup for a campaign')),
                ('campaign_unsubscribe_success', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Success page for unsubscription')),
            ],
            options={
                'verbose_name': 'Birdsong settings',
            },
        ),
    ]
