# Generated by Django 3.2.16 on 2023-03-09 10:20

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('birdsong', '0009_auto_20221222_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleoptinsettings',
            name='double_opt_in_enabled',
            field=models.BooleanField(default=False, help_text='The settings below are only applied if double opt-in is enabled.', verbose_name='Enable double opt-in'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='The name of the campaign', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='receipts',
            field=models.ManyToManyField(through='birdsong.Receipt', to='birdsong.Contact', verbose_name='receipts'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(0, 'unsent'), (1, 'sending'), (2, 'sent'), (3, 'failed')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.TextField(verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='confirmed_at',
            field=models.DateTimeField(null=True, verbose_name='confirmed at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='birdsong.ContactTag', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
