# Generated by Django 4.1.5 on 2023-03-12 15:04

from django.db import migrations, models

def activate_all_contacts(apps, schema_editor):
    """Activates all existing contacts"""
    Contact = apps.get_model('birdsong', 'Contact')
    contacts = Contact.objects.all().exclude(is_active=True)
    for contact in contacts:
        contact.is_active = True
    Contact.objects.bulk_update(contacts, ['is_active'])

class Migration(migrations.Migration):
    """This migration is necessary because initially we want to set `contact.is_active` field to True during migrations.
    
    This should happen because there was no activation process for contacts in the past and so it makes sense to treat
    all existing contacts as already active.
    
    Explanation of why a bare AddField/AlterFiel solution wouldn't work:
        It might be tempting to implement this by two migrations where AddField sets the default to True in the first
        migration and then in the second migration have an AlterField operation that sets `contact.is_active` default
        back to False. Unfortunately that solution would only work until the two migrations get squashed.

    NOTE: This migration will activate all existing contacts and it will "survive" migration squashing.
    """

    dependencies = [
        ('birdsong', '0009_subscribe_form_support'),
    ]

    operations = [
        migrations.RunPython(
            code=activate_all_contacts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
