# Generated by Django 3.2.16 on 2022-12-22 16:37

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0010_doubleoptinsettings_campaign_unsubscribe_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='doubleoptinsettings',
            name='confirmation_email_body',
            field=wagtail.fields.RichTextField(default='Click the following link if you want register for our newsletter. Otherwise no action is neccessary.', help_text='This Text is part of the e-mail that is sent after registration for a campaign', verbose_name='Content of confirmation e-mail'),
        ),
    ]
