# Generated by Django 3.2.16 on 2023-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0011_auto_20221222_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='confirmed_at',
            field=models.DateTimeField(null=True, verbose_name='confirmed at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
    ]
