# Generated by Django 2.2.10 on 2020-03-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailbirdsong', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultEmail',
        ),
    ]
